#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="silly"
device="silly"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

echo "$module - major: " $major

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[bwl]
rm -f /dev/${device}cp

mknod /dev/${device}b c $major 0
mknod /dev/${device}w c $major 1
mknod /dev/${device}l c $major 2
mknod /dev/${device}cp c $major 3
chgrp $group /dev/${device}[bwl]
chgrp $group /dev/${device}cp
chmod $mode  /dev/${device}[bwl]
chmod $mode  /dev/${device}cp

